# Generated by Django 5.2 on 2025-04-20 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytechadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicename',
            name='about_service',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
