# Generated by Django 5.2 on 2025-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytechadmin', '0002_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicename',
            name='service_img',
            field=models.ImageField(blank=True, null=True, upload_to='serviceImg'),
        ),
    ]
