# Generated by Django 5.2 on 2025-06-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytechadmin', '0004_enquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
